# Python basics

Variables and Strings

In [1]:
msg = "Hello World"

In [2]:
msg

'Hello World'

In [3]:
print(msg)

Hello World


In [4]:
var1 = 'Hello'

In [5]:
var2 = "World"

In [6]:
var3 = var1 + var2

In [7]:
var3

'HelloWorld'

In [8]:
var4 = 4

In [9]:
var5 = 6

In [10]:
var4/var5

0.6666666666666666

## Lists

In [11]:
users = ['ram', 'shyam', 'bob']

In [12]:
users

['ram', 'shyam', 'bob']

In [13]:
users[0]

'ram'

In [14]:
users[0]

'ram'

In [15]:
users.append('simon')

In [16]:
users

['ram', 'shyam', 'bob', 'simon']

In [17]:
users.insert(0,'joe')

In [18]:
users

['joe', 'ram', 'shyam', 'bob', 'simon']

In [19]:
users.remove('ram')

In [20]:
users

['joe', 'shyam', 'bob', 'simon']

In [21]:
del users[-1]

In [22]:
users

['joe', 'shyam', 'bob']

In [23]:
del users[2]

In [24]:
users

['joe', 'shyam']

In [25]:
top_user =  users.pop()

In [26]:
top_user

'shyam'

In [27]:
len(users)

1

In [28]:
users.sort()

In [29]:
users

['joe']

In [30]:
users.sort(reverse=True)

In [31]:
users

['joe']

In [32]:
for user in users:
 print(user)    
    


    

joe


In [33]:
for number in range(10, 501):
    print(number)

10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
28

In [34]:
numbers = list(range(10, 501))

In [35]:
numbers

[10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191

In [36]:
min(numbers)

10

In [37]:
max(numbers)

500

In [38]:
sum(numbers)

125205

In [39]:
users = ['joe', 'joe', 'ram', 'shyam', 'bob', 'simon', 'simon']

In [40]:
some_users = users[1:4]

In [41]:
some_users

['joe', 'ram', 'shyam']

In [42]:
some_users = users[:]

In [43]:
some_users

['joe', 'joe', 'ram', 'shyam', 'bob', 'simon', 'simon']

In [44]:
users[:3]

['joe', 'joe', 'ram']

In [45]:
users[-3:]

['bob', 'simon', 'simon']

## Dictionaries

In [46]:
dic = {'user1':'ram', 'user2':'shyam'}

In [47]:
dic

{'user1': 'ram', 'user2': 'shyam'}

In [48]:
dic['user1']

'ram'

In [49]:
for users in dic.keys():
    print(users)

user1
user2


In [50]:
for users_values in dic.values():
    print(users_values)

ram
shyam


In [51]:
len(dic)

2

In [52]:
dic1 = {'user1':'bob', 'user2':'Simon'}

In [53]:
users = []

In [54]:
users.append(dic)

In [55]:
users.append(dic1)

In [56]:
users

[{'user1': 'ram', 'user2': 'shyam'}, {'user1': 'bob', 'user2': 'Simon'}]

## Loops

In [57]:
message = 'Please enter something'

In [58]:
input_user = input(message)

Please enter somethingHello


In [59]:
input_user

'Hello'

In [62]:
i = 0

while i < 5:
    print(i)
    i = i + 1

    

0
1
2
3
4


In [63]:
pets = ['dog', 'cat', 'dog', 'fish', 'cat',
            'rabbit', 'cat']
print(pets)
while 'cat' in pets:
    pets.remove('cat')
print(pets)

['dog', 'cat', 'dog', 'fish', 'cat', 'rabbit', 'cat']
['dog', 'dog', 'fish', 'rabbit']


## Functions

In [69]:
def fun1(var1='default'):
    print(var1)
    
    

In [70]:
fun1('hello')

hello


In [71]:
fun1()

default


In [72]:
def greet_users(names):
    """Print a simple greeting to everyone."""
    for name in names:
        msg = "Hello, " + name + "!"
        print(msg)

In [73]:
usernames = ['hannah', 'ty', 'margot']

In [74]:
greet_users(usernames)

Hello, hannah!
Hello, ty!
Hello, margot!


In [84]:
def fun2(var1='default'):
    return 4
    

In [85]:
var4 = fun2()

In [86]:
var4

4

In [92]:
class Car():

    """A simple attempt to model a car."""
    def __init__(self, make, model, year):
        """Initialize car attributes."""
        self.make = make
        self.model = model
        self.year = year
        # Fuel capacity and level in gallons.
        self.fuel_capacity = 15
        self.fuel_level = 0
        
    def fill_tank(self):
        """Fill gas tank to capacity."""
        self.fuel_level = self.fuel_capacity
        print(self.fuel_level)
        print("Fuel tank is full.")
        
    def drive(self):
        """Simulate driving."""
        print("The car is moving.")


In [93]:
my_car = Car('audi', 'a4', '2020')

In [94]:
my_car.fill_tank()

15
Fuel tank is full.


## Numpy

In [96]:
import numpy as np

In [97]:
a = np.array([1,2,3])

In [98]:
a

array([1, 2, 3])

In [99]:
b = np.array([4,5,6])

In [100]:
a + b

array([5, 7, 9])

In [101]:
a * b

array([ 4, 10, 18])

In [102]:
a == b

array([False, False, False])

In [103]:
a.sum()

6

In [104]:
a.min()

1

In [105]:
arr1 = np.zeros((3,4))

In [107]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
arr2 = np.ones((2,3,4),dtype=np.int16)

In [109]:
arr2

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [110]:
np.exp(b)

array([ 54.59815003, 148.4131591 , 403.42879349])

In [111]:
np.sqrt(b)

array([2.        , 2.23606798, 2.44948974])

In [112]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [113]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [114]:
a[0:2]

array([1, 2])

In [115]:
np.transpose(a)

array([1, 2, 3])

## Pandas

In [116]:
import pandas as pd

In [119]:
df = pd.DataFrame(
              {"a" : [4 ,5, 6],
               "b" : [7, 8, 9],
               "c" : [10, 11, 12]},
            index = [1, 2, 3])

In [120]:
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [121]:
df.describe()

a    b     c
count  3.0  3.0   3.0
mean   5.0  8.0  11.0
std    1.0  1.0   1.0
min    4.0  7.0  10.0
25%    4.5  7.5  10.5
50%    5.0  8.0  11.0
75%    5.5  8.5  11.5
max    6.0  9.0  12.0

In [122]:
df['a'].max()

6

In [123]:
df['a'].count()

3

In [124]:
df.dropna()

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [125]:
df.fillna(3)

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12